apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: quay.io/mxinden/self-service-monitoring-sample-app:v2.0.0
        name: sample-app
        ports:
        - containerPort: 8080
          name: http-main
