apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  endpoints:
  - interval: 30s
    port: http-main
  selector:
    matchLabels:
      app: sample-app
