apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  # clusterIP: None
  ports:
  - name: http-main
    port: 8080
    targetPort: 8080
  selector:
    app: sample-app
